### ISSUE TITLE
Dependency status didn't load

### ISSUE THREAD

**Issue by AugustasV** [1000ch/whale#75]
Couldn't check dependency status by link in README.md file, doesn't load.
```
FetchError: invalid json response body at https://status.david-dm.org/gh/1000ch/whale?type=dev reason: Unexpected token < in JSON at position 0
    at /home/node/app/node_modules/node-fetch/lib/body.js:48:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 1)
    at async Promise.all (index 0)
```

**Comment by 1000ch** [comment]
It sometimes happens due to the instability of https://david-dm.org/, thank you for your report!
